server:
    port: 8001

spring:
    redis:
        host: 127.0.0.1
        port: 6379
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/myweb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource


jerry:
    jwt:
        header: Authorization
        expire: 604800 #7?????
        secret: dwdasd12318927219837f123fa768f81 #??32?????